### ISSUE TITLE
how to install your gnuradio

### ISSUE THREAD

**Issue by sunwit** [kit-cel/gnuradio#33]
hello, when i manually install gnuradio from your repository, i did make test, but it is stuck at the following test:
300/356 Test #300: qa_ofdm_frame_equalizer_vcvc .......................   Passed    0.33 sec
        Start 301: qa_vblast_loopbac

**Comment by sunwit** [comment]
dear author, 

after i omit the make test process, my gnuradio can work. but, the ofdm receiver or transmitter does not have mimo features.

**Comment by primercuervo** [comment]
@sunwit MIMO is not yet part of the main GNU Radio Tree, as you can see the open PR here https://github.com/kit-cel/gnuradio/pull/32. You can either check out that development branch or wait until it is merged into master. This work will probably be upstreamed to the original GNU Radio repository, but a certain date or time range for when that might happen is something that can't be promised. 

Have a look at the documentation here: https://github.com/kit-cel/gnuradio/pull/32

**Comment by primercuervo** [comment]
@sunwit The PR that I references regards only the channel estimation, not the Tx-Rx. Sorry about that. A quick look at the code suggests that the MIMO-OFDM receiver and transmitter block is under construction in the https://github.com/kit-cel/gnuradio/commits/mimo_hier_block branch. I believe it is just safer to assume that this feature is not yet available, and therefore there is no real issue to be reported.

**Comment by MLsmd** [comment]
Thanks @primercuervo for clearing that up! The https://github.com/kit-cel/gnuradio/commits/mimo_hier_block branch includes indeed the current development of the MIMO-OFDM. So if you want to check it out: The MIMO-OFDM transceiver is already working without sync, and I am implementing the sync functionalities at the moment (actually it is finished but not fully tested, yet).

**Comment by sunwit** [comment]
Thanks @primercuervo  @MoritzLucaSchmid  for explanation.
